-- Supabase Schema for Gym It Up With
-- Run this script in the Supabase SQL Editor.

-- Create profiles table linked to Supabase Auth users
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create quotes table
CREATE TABLE IF NOT EXISTS public.quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    author TEXT DEFAULT 'Coach',
    scheduled_date DATE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for quotes
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Create gallery table
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    image_url TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('transformations', 'gym_sessions', 'events', 'competitions')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for gallery
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- Create videos table
CREATE TABLE IF NOT EXISTS public.videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    video_url TEXT NOT NULL, -- Direct video link or YouTube embed link
    thumbnail_url TEXT,
    description TEXT,
    category TEXT NOT NULL CHECK (category IN ('workout', 'tutorial', 'transformation', 'event')),
    is_featured BOOLEAN DEFAULT false,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for videos
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;

-- Create blogs table
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL,
    excerpt TEXT,
    cover_image TEXT,
    category TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for blogs
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Create events table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    location TEXT NOT NULL,
    cover_image TEXT,
    registration_link TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for events
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Create achievements table
CREATE TABLE IF NOT EXISTS public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    achievement_date DATE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for achievements
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;

-- Create contact_requests table
CREATE TABLE IF NOT EXISTS public.contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'responded', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for contact_requests
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

-- Create home_content table
CREATE TABLE IF NOT EXISTS public.home_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    cta_text TEXT,
    cta_url TEXT,
    hero_image_url TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for home_content
ALTER TABLE public.home_content ENABLE ROW LEVEL SECURITY;

-- Create carousel_slides table
CREATE TABLE IF NOT EXISTS public.carousel_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id TEXT NOT NULL,
    caption TEXT,
    "order" INT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for carousel_slides
ALTER TABLE public.carousel_slides ENABLE ROW LEVEL SECURITY;

-- Create chat_links table
CREATE TABLE IF NOT EXISTS public.chat_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('chatbot', 'whatsapp', 'phone')),
    url TEXT NOT NULL,
    "order" INT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for chat_links
ALTER TABLE public.chat_links ENABLE ROW LEVEL SECURITY;

-- Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for settings
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;


--------------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) POLICIES
--------------------------------------------------------------------------------

-- Helper function to check if the current user is an admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND (role = 'admin' OR role = 'super_admin')
        )
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles: Admin read/write own profile, super_admin read all
CREATE POLICY "Allow public read of profiles" ON public.profiles
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow admin manage profiles" ON public.profiles
    FOR ALL TO authenticated USING (auth.uid() = id OR public.is_admin());

-- Quotes: Public read active, Admin all
CREATE POLICY "Allow public read active quotes" ON public.quotes
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage quotes" ON public.quotes
    FOR ALL TO authenticated USING (public.is_admin());

-- Gallery: Public read active, Admin all
CREATE POLICY "Allow public read active gallery" ON public.gallery
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage gallery" ON public.gallery
    FOR ALL TO authenticated USING (public.is_admin());

-- Videos: Public read active, Admin all
CREATE POLICY "Allow public read active videos" ON public.videos
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage videos" ON public.videos
    FOR ALL TO authenticated USING (public.is_admin());

-- Blogs: Public read active, Admin all
CREATE POLICY "Allow public read active blogs" ON public.blogs
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage blogs" ON public.blogs
    FOR ALL TO authenticated USING (public.is_admin());

-- Events: Public read active, Admin all
CREATE POLICY "Allow public read active events" ON public.events
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage events" ON public.events
    FOR ALL TO authenticated USING (public.is_admin());

-- Achievements: Public read active, Admin all
CREATE POLICY "Allow public read active achievements" ON public.achievements
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage achievements" ON public.achievements
    FOR ALL TO authenticated USING (public.is_admin());

-- Home content: Public read active, Admin all
CREATE POLICY "Allow public read active home_content" ON public.home_content
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage home_content" ON public.home_content
    FOR ALL TO authenticated USING (public.is_admin());

-- Carousel slides: Public read active, Admin all
CREATE POLICY "Allow public read active carousel_slides" ON public.carousel_slides
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage carousel_slides" ON public.carousel_slides
    FOR ALL TO authenticated USING (public.is_admin());

-- Chat links: Public read active, Admin all
CREATE POLICY "Allow public read active chat_links" ON public.chat_links
    FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow admin manage chat_links" ON public.chat_links
    FOR ALL TO authenticated USING (public.is_admin());

-- Contact Requests: Public can insert, Admin can manage (no public select)
CREATE POLICY "Allow public submit contact request" ON public.contact_requests
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow admin manage contact requests" ON public.contact_requests
    FOR ALL TO authenticated USING (public.is_admin());


--------------------------------------------------------------------------------
-- AUTOMATIC PROFILE CREATION ON SIGN-UP (Trigger)
--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, role)
    VALUES (new.id, new.email, 'admin'); -- Default all signed up users to admin for convenience (can be managed by super_admin)
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


--------------------------------------------------------------------------------
-- STORAGE BUCKETS SETUP SUGGESTION
--------------------------------------------------------------------------------
-- Run this in Supabase client or dashboard:
-- Create buckets: 'gallery', 'videos', 'blogs', 'events', 'achievements', 'popups'
-- Ensure they are set to Public, or set public policies on storage.objects:
-- e.g. CREATE POLICY "Allow public read" ON storage.objects FOR SELECT USING (bucket_id IN ('gallery', 'videos', 'blogs', 'events', 'achievements', 'popups'));
-- e.g. CREATE POLICY "Allow admin manage" ON storage.objects FOR ALL TO authenticated USING (public.is_admin());

--------------------------------------------------------------------------------
-- DAILY POPUPS TABLE
--------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_popups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    cta_text TEXT NOT NULL DEFAULT 'Start Your Journey',
    cta_link TEXT NOT NULL DEFAULT '/contact',
    image_url TEXT,
    popup_type TEXT NOT NULL DEFAULT 'motivation' CHECK (popup_type IN ('motivation', 'promo', 'event', 'tip')),
    day_of_week TEXT CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
    scheduled_date DATE,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for daily_popups
ALTER TABLE public.daily_popups ENABLE ROW LEVEL SECURITY;

-- Allow public read of active popups
CREATE POLICY "Allow public read active popups" ON public.daily_popups
    FOR SELECT TO public USING (status = 'active');

-- Allow admin manage popups
CREATE POLICY "Allow admin manage popups" ON public.daily_popups
    FOR ALL TO authenticated USING (public.is_admin());

