-- Migration: Add content tables for dynamic site
-- Home page content
CREATE TABLE IF NOT EXISTS public.home_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    cta_text TEXT,
    cta_url TEXT,
    bg_image_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Carousel slides
CREATE TABLE IF NOT EXISTS public.carousel_slides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id TEXT NOT NULL,
    caption TEXT,
    "order" INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Settings (key/value)
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Chat links (multiple rows)
CREATE TABLE IF NOT EXISTS public.chat_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('chatbot','whatsapp','phone')),
    url TEXT NOT NULL,
    "order" INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Admin audit log
CREATE TABLE IF NOT EXISTS public.admin_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Enable RLS for new tables
ALTER TABLE public.home_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carousel_slides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit ENABLE ROW LEVEL SECURITY;

-- Policies: public read where appropriate, admin manage all
CREATE POLICY "Allow public read home_content" ON public.home_content FOR SELECT TO public USING (true);
CREATE POLICY "Allow admin manage home_content" ON public.home_content FOR ALL TO authenticated USING (public.is_admin());

CREATE POLICY "Allow public read carousel" ON public.carousel_slides FOR SELECT TO public USING (true);
CREATE POLICY "Allow admin manage carousel" ON public.carousel_slides FOR ALL TO authenticated USING (public.is_admin());

CREATE POLICY "Allow admin manage settings" ON public.settings FOR ALL TO authenticated USING (public.is_admin());

CREATE POLICY "Allow admin manage chat_links" ON public.chat_links FOR ALL TO authenticated USING (public.is_admin());
CREATE POLICY "Allow public read chat_links" ON public.chat_links FOR SELECT TO public USING (true);

CREATE POLICY "Allow admin manage audit" ON public.admin_audit FOR ALL TO authenticated USING (public.is_admin());
